spring:
  boot:
    admin:
      client:
        url: http://localhost:1112

management:
  endpoints:
    web:
      exposure:
        include: "*"
message: "This is rest message from config server"  
